// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArI2uvhvA75WoNIfiASYWJuCiJZK3VOSA',
    appId: '1:522690579720:web:5d1ccfda8992531b7eb0bd',
    messagingSenderId: '522690579720',
    projectId: 'flutter-a4919',
    authDomain: 'flutter-a4919.firebaseapp.com',
    storageBucket: 'flutter-a4919.appspot.com',
    measurementId: 'G-WBPNF45RN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtXe-0NJ8gfB_pFoNiTVy8NBDqOGk2WAs',
    appId: '1:522690579720:android:92699da6cec60a087eb0bd',
    messagingSenderId: '522690579720',
    projectId: 'flutter-a4919',
    storageBucket: 'flutter-a4919.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_xLBhGlf6_KX-1GlEyWh_kYEPiiAeLc4',
    appId: '1:522690579720:ios:549380d46665c2e47eb0bd',
    messagingSenderId: '522690579720',
    projectId: 'flutter-a4919',
    storageBucket: 'flutter-a4919.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
